<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Leads Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        h1 {
            color: #063A1C;
            text-align: center;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #063A1C;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <h1>Leads Export Report</h1>
    <p><strong>Generated:</strong> {{ date('Y-m-d H:i:s') }}</p>
    <p><strong>Total Records:</strong> {{ count($leads) }}</p>
    
    <table>
        <thead>
            <tr>
                @foreach($headers as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($leads as $lead)
                <tr>
                    @foreach($fields as $field)
                        <td>
                            @if($field === 'assigned_to')
                                {{ $lead->activeAssignments->first()?->assignedTo->name ?? 'Unassigned' }}
                            @elseif($field === 'status')
                                {{ ucfirst(str_replace('_', ' ', $lead->status)) }}
                            @elseif(in_array($field, ['created_at', 'updated_at', 'last_contacted_at', 'marked_dead_at']))
                                {{ $lead->$field ? $lead->$field->format('Y-m-d H:i') : 'N/A' }}
                            @elseif($field === 'marked_dead_by')
                                {{ $lead->marked_dead_by ? \App\Models\User::find($lead->marked_dead_by)?->name ?? 'N/A' : 'N/A' }}
                            @else
                                {{ $lead->$field ?? 'N/A' }}
                            @endif
                        </td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p>Generated by Base CRM - {{ date('Y') }}</p>
    </div>
</body>
</html>

